def test_daily_loss_limit():
    ...

def test_max_position_limit():
    ...

def test_order_size_limit():
    ...

def test_trade_blocked_when_limit_exceeded():
    ...

def test_risk_summary():
    ...