def test_validate_strategy():
    ...

def test_missing_configuration():
    ...

def test_invalid_parameters():
    ...

def test_dependency_validation():
    ...

def test_validation_report():
    ...