def test_execute_returns_open_position(): ...


def test_update_price_changes_ltp(): ...


def test_close_returns_closed_position(): ...


def test_position_quantity_preserved(): ...


def test_position_average_price_preserved(): ...


def test_update_price_preserves_position_id(): ...


def test_close_preserves_position_id(): ...


def test_close_sets_closed_timestamp(): ...


def test_update_price_does_not_close_position(): ...


def test_execute_creates_unique_positions(): ...
