def test_runtime_metrics_cycles():
    ...

def test_runtime_metrics_orders():
    ...

def test_runtime_metrics_positions():
    ...

def test_runtime_metrics_exceptions():
    ...

def test_runtime_metrics_snapshot():
    ...