def test_release_checklist_complete():
    ...

def test_required_modules_present():
    ...

def test_configuration_valid():
    ...

def test_release_metadata():
    ...

def test_release_ready():
    ...