def test_release_manager_prepare(): ...


def test_release_manager_validate(): ...


def test_release_manager_publish(): ...


def test_release_manager_rollback(): ...


def test_release_manager_status(): ...
