def test_version_manager_current():
    ...

def test_version_manager_increment_patch():
    ...

def test_version_manager_increment_minor():
    ...

def test_version_manager_increment_major():
    ...

def test_version_manager_compare():
    ...