def test_full_regression_passes():
    ...

def test_strategy_regression():
    ...

def test_reporting_regression():
    ...

def test_execution_regression():
    ...

def test_regression_summary():
    ...