def test_load_tester_initializes():
    ...

def test_load_tester_runs():
    ...

def test_load_tester_records_throughput():
    ...

def test_load_tester_stops():
    ...

def test_load_tester_summary():
    ...