def test_recovery_manager_start():
    ...

def test_recovery_manager_recover():
    ...

def test_recovery_manager_records_failure():
    ...

def test_recovery_manager_reset():
    ...

def test_recovery_manager_summary():
    ...