def test_circuit_breaker_closed(): ...


def test_circuit_breaker_open(): ...


def test_circuit_breaker_half_open(): ...


def test_circuit_breaker_reset(): ...


def test_circuit_breaker_rejects_requests(): ...
