def test_portfolio_service_starts_empty(): ...


def test_portfolio_service_add_position(): ...


def test_portfolio_service_remove_position(): ...


def test_portfolio_service_returns_positions(): ...


def test_portfolio_service_position_count(): ...


def test_portfolio_service_clear_positions(): ...


def test_portfolio_service_contains_position(): ...


def test_portfolio_service_duplicate_positions(): ...


def test_portfolio_service_remove_unknown_position(): ...


def test_portfolio_service_reset(): ...
