def test_application_bootstrap():
    ...

def test_application_start_stop():
    ...

def test_application_restart():
    ...

def test_application_initializes_dependencies():
    ...

def test_application_shutdown_releases_resources():
    ...