def test_full_paper_trading_session(): ...


def test_multiple_trades_in_session(): ...


def test_session_generates_report(): ...


def test_session_updates_portfolio_metrics(): ...


def test_session_closes_cleanly(): ...
