def test_replay_loads_market_data():
    ...

def test_replay_runs_full_day():
    ...

def test_replay_generates_trades():
    ...

def test_replay_handles_empty_dataset():
    ...

def test_replay_summary():
    ...