def test_broker_session_connect():
    ...

def test_broker_session_disconnect():
    ...

def test_broker_session_reconnect():
    ...

def test_broker_session_is_connected():
    ...

def test_broker_session_reset():
    ...