def test_risk_guard_daily_loss_limit():
    ...

def test_risk_guard_max_position_size():
    ...

def test_risk_guard_max_open_positions():
    ...

def test_risk_guard_blocks_trade():
    ...

def test_risk_guard_allows_trade():
    ...