def test_order_validator_accepts_valid_order():
    ...

def test_order_validator_rejects_invalid_quantity():
    ...

def test_order_validator_rejects_invalid_price():
    ...

def test_order_validator_rejects_unknown_symbol():
    ...

def test_order_validator_returns_validation_result():
    ...