def test_application_config_default_values():
    ...

def test_application_config_broker():
    ...

def test_application_config_market():
    ...

def test_application_config_reporting():
    ...

def test_application_config_runtime():
    ...