def test_environment_defaults_to_paper(): ...


def test_environment_reads_env_variable(): ...


def test_environment_is_production(): ...


def test_environment_is_paper(): ...


def test_environment_invalid_mode(): ...
