def test_reconnect_manager_initial_state():
    ...

def test_reconnect_manager_connect():
    ...

def test_reconnect_manager_disconnect():
    ...

def test_reconnect_manager_retry_count():
    ...

def test_reconnect_manager_reset():
    ...