def test_market_event_created():
    ...

def test_market_event_symbol():
    ...

def test_market_event_price():
    ...

def test_market_event_timestamp():
    ...

def test_market_event_serialization():
    ...