def test_report_contains_trades():
    ...

def test_report_contains_pnl():
    ...

def test_report_contains_metrics():
    ...

def test_report_exports():
    ...

def test_report_complete():
    ...