def test_session_starts_cleanly(): ...


def test_session_processes_market_open(): ...


def test_session_tracks_runtime(): ...


def test_session_handles_market_close(): ...


def test_session_summary(): ...
