def test_public_api_documented():
    ...

def test_modules_documented():
    ...

def test_classes_documented():
    ...

def test_examples_present():
    ...

def test_api_reference_complete():
    ...