def test_yaml_configuration():
    ...

def test_environment_configuration():
    ...

def test_default_configuration():
    ...

def test_configuration_validation():
    ...

def test_configuration_example_complete():
    ...