"""
=========================================================
Trading Operating System (TOS)
Module      : Enumerations
Version     : 1.0.0
Author      : Rajesh Varma
Description : Common enumerations used throughout TOS.
=========================================================
"""

from enum import StrEnum

# ==========================================================
# SIGNAL
# ==========================================================


class Signal(StrEnum):
    """Trading signal generated by Strategy Engine."""

    NONE = "NONE"

    BUY_CE = "BUY_CE"
    BUY_PE = "BUY_PE"

    EXIT = "EXIT"


# ==========================================================
# DECISION STATUS
# ==========================================================


class DecisionStatus(StrEnum):
    """Lifecycle of a strategy decision."""

    NO_SIGNAL = "NO_SIGNAL"
    VALID = "VALID"
    BLOCKED = "BLOCKED"
    EXECUTED = "EXECUTED"
    ERROR = "ERROR"


# ==========================================================
# EXIT REASON
# ==========================================================


class ExitReason(StrEnum):
    """Trade exit reason."""

    NONE = "NONE"
    STOP_LOSS = "STOP_LOSS"
    TRAILING_SL = "TRAILING_SL"
    FORCE_EXIT = "FORCE_EXIT"
    TARGET = "TARGET"
    MANUAL = "MANUAL"
    END_OF_DATA = "END_OF_DATA"


# ==========================================================
# ORDER SIDE
# ==========================================================


class OrderSide(StrEnum):
    """Order direction."""

    BUY = "BUY"
    SELL = "SELL"


# ==========================================================
# ORDER STATUS
# ==========================================================


class OrderStatus(StrEnum):
    """Lifecycle of an order."""

    CREATED = "CREATED"
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


# ==========================================================
# TRADE STATUS
# ==========================================================


class TradeStatus(StrEnum):
    """Lifecycle of a trade."""

    CREATED = "CREATED"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


# ==========================================================
# OPTION TYPE
# ==========================================================


class OptionType(StrEnum):
    """Option contract type."""

    CE = "CE"
    PE = "PE"


# ==========================================================
# BROKER
# ==========================================================


class Broker(StrEnum):
    """Supported brokers."""

    DHAN = "DHAN"
    ZERODHA = "ZERODHA"


# ==========================================================
# TRADING MODE
# ==========================================================


class TradingMode(StrEnum):
    """Trading environment."""

    PAPER = "PAPER"
    LIVE = "LIVE"


# ==========================================================
# MARKET STATE
# ==========================================================


class MarketState(StrEnum):
    """Current market state."""

    PRE_OPEN = "PRE_OPEN"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


# ==========================================================
# LOG LEVEL
# ==========================================================


class LogLevel(StrEnum):
    """Application log levels."""

    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
