"""
Trading event names.
"""

from enum import StrEnum


class Event(StrEnum):
    MARKET_TICK = "MARKET_TICK"
    CANDLE_COMPLETED = "CANDLE_COMPLETED"
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    RISK_APPROVED = "RISK_APPROVED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    POSITION_UPDATED = "POSITION_UPDATED"
    TRADE_CLOSED = "TRADE_CLOSED"
