def test_session_runner_start():
    ...

def test_session_runner_market_open():
    ...

def test_session_runner_market_close():
    ...

def test_session_runner_shutdown():
    ...

def test_session_runner_runtime():
    ...