def test_certifier_initializes():
    ...

def test_certifier_runs_complete_session():
    ...

def test_certifier_collects_statistics():
    ...

def test_certifier_generates_summary():
    ...

def test_certifier_passes():
    ...