def test_generate_training_windows(): ...


def test_generate_validation_windows(): ...


def test_overlapping_windows(): ...


def test_non_overlapping_windows(): ...


def test_window_statistics(): ...
